In 34 music
iDommel/indieStudio pull request #20
Opened 2022-06-01 16:23 UTC by rox51124

2022-06-01 17:07 UTC, iDommel reviewed
Nice job, please merge dev and fix conflicts before approval

2022-06-02 13:10 UTC, iDommel requested changes
Some minor changes on method names

2022-06-02 13:10 UTC, iDommel commented on src/Music.cpp
> +        delete _music.release();
I don't think you need to specifically delete this as it is a unique ptr

2022-06-02 13:10 UTC, iDommel commented on src/Music.hpp
> +            void PlayMusic();
don't capitalize method names, that's C style coding

2022-06-03 09:03 UTC, iDommel approved these changes

2022-06-03 09:36 UTC, MauxC approved these changes

2022-06-06 12:14 UTC, iDommel commented
I Just fixed the merge conflicts, I'm merging now

2022-06-06 12:14 UTC, merged