ADDED: AudioDevice Class
iDommel/indieStudio pull request #21
Opened 2022-06-01 16:24 UTC by rox51124

2022-06-01 17:03 UTC, iDommel requested changes
A few minor changes, and please merge dev into this branch to fix the conflicts

2022-06-01 17:03 UTC, iDommel commented on src/AudioDevice.hpp
> +#include <raylib.h>
I think we can avoid that include here and put it in the .cpp file

2022-06-01 17:03 UTC, iDommel commented on test_functions/TestAudioDevice.cpp
> +    //InitAudioDevice();                  // Initialize audio device
I think you forgot to test your class, or at least it's not used in the test file

2022-06-02 09:49 UTC, iDommel submitted a review, later dismissed

2022-06-02 12:14 UTC, MauxC commented on src/AudioDevice.hpp
> +            void Volume(float volume);
setVolume & isReady would be better names for methods

2022-06-02 12:16 UTC, MauxC requested changes

2022-06-02 12:16 UTC, MauxC commented on src/exceptions/AudioDeviceError.hpp
> +class AudioDeviceError {
Namespace indie is missing

2022-06-02 12:33 UTC, MauxC approved these changes

2022-06-02 12:39 UTC, iDommel approved these changes

2022-06-02 12:39 UTC, merged