ADDING: shape2D circle and rectangle
iDommel/indieStudio pull request #24
Opened 2022-06-03 09:19 UTC by mangasteak

2022-06-03 09:23 UTC, antoinepnt requested changes

2022-06-03 09:23 UTC, antoinepnt commented on src/Shape2D.cpp
> +indie::Shape2D::Shape2D()
Do namespace indie  {your code} instead

2022-06-03 09:23 UTC, antoinepnt commented on src/Shape2D.hpp
> +         */
You can use "///" instead of "/**" when there's only one line

2022-06-03 09:23 UTC, antoinepnt commented on src/Shape2D.hpp
> +        void drawCircle(int centerX, int centerY, float radius, Color color);
Maybe add a default color to the function's prototype (WHITE for example)

2022-06-03 09:44 UTC, antoinepnt approved these changes

2022-06-03 22:56 UTC, iDommel commented on src/Shape2D.hpp
> +        static void drawCircle(int centerX, int centerY, float radius, Color color = WHITE);
Where is the WHITE color defined ? Doest this compile ?

2022-06-06 12:16 UTC, iDommel approved these changes

2022-06-06 12:16 UTC, merged