ADDED: ModelAnimation class in ModelAnimation.hpp
iDommel/indieStudio pull request #28
Opened 2022-06-08 13:06 UTC by Mfolio2004

2022-06-08 13:10 UTC, mangasteak commented on src/main.cpp
>      // Main game loop
are the comments inside wanted ? is it really necessary N

2022-06-08 13:11 UTC, mangasteak reviewed
checkout my comment ^^. everything else is fine for me

2022-06-08 13:13 UTC, mangasteak reviewed
same thing but different file

2022-06-08 13:13 UTC, mangasteak commented on test_functions/TestModelAnimation.cpp
> +
same comment since the last time. are the comments necessary , even thought it's probably a prebuild func isn't it ? (excuse me if it isn't)

2022-06-08 13:17 UTC, mangasteak submitted a review, later dismissed
noice

2022-06-08 13:47 UTC, MauxC requested changes
Rename modelAnimation.cpp & hpp with a uppercase M

2022-06-08 13:47 UTC, MauxC commented on src/modelAnimation.cpp
> +indie::ModelAnimation::~ModelAnimation()
you should unload the model animation if not already done

2022-06-09 12:50 UTC, mangasteak approved these changes

2022-06-09 15:14 UTC, merged