In 99 map generation
iDommel/indieStudio pull request #32
Opened 2022-06-10 16:07 UTC by MauxC

2022-06-11 16:21 UTC, rox51124 approved these changes

2022-06-13 08:45 UTC, Varriss requested changes

2022-06-13 08:45 UTC, Varriss commented on src/systems/GameSystem.hpp
> +        static void generateMap(const std::string &filename, IScene &scene);
Add a -> TODO: trasnform method to none static to avoid forwarding the scene.
Will be done at a later time...

2022-06-13 08:45 UTC, Varriss commented on src/generateMap.cpp
> +        "assets/ground_asset/sand_asset_basic/sand_asset_basic"
Just use a better algorythm ...

2022-06-14 12:34 UTC, Varriss submitted a review, later dismissed

2022-06-14 14:35 UTC, rox51124 submitted a review, later dismissed

2022-06-14 14:57 UTC, Varriss submitted a review, later dismissed

2022-06-14 15:37 UTC, merged