In 179 music update
iDommel/indieStudio pull request #33
Opened 2022-06-14 09:45 UTC by rox51124

2022-06-14 11:49 UTC, iDommel requested changes

2022-06-14 11:49 UTC, iDommel commented on src/AudioDevice.cpp
> +    InitAudioDevice();
It would be better if there was a verification to check if audiodevice wasn't already initialized.

2022-06-14 15:03 UTC, Varriss submitted a review, later dismissed

2022-06-15 12:30 UTC, iDommel approved these changes

2022-06-16 11:49 UTC, iDommel submitted a review, later dismissed

2022-06-16 13:20 UTC, Varriss requested changes

2022-06-16 13:20 UTC, Varriss commented on src/systems/GameSystem.cpp
> +<<<<<<< HEAD
Remove shit pls

2022-06-16 13:20 UTC, Varriss commented on src/systems/GameSystem.cpp
> +=======
Shit

2022-06-16 13:20 UTC, Varriss commented on src/systems/GameSystem.cpp
> +<<<<<<< HEAD
Shit

2022-06-16 13:20 UTC, Varriss commented on src/systems/GameSystem.cpp
> +=======
Shit

2022-06-16 13:20 UTC, Varriss commented on src/systems/GameSystem.cpp
> +>>>>>>> origin/dev
Shit

2022-06-16 13:20 UTC, Varriss commented on src/systems/GameSystem.cpp
> +<<<<<<< HEAD
Shit

2022-06-16 13:20 UTC, Varriss commented on src/systems/GameSystem.cpp
> +>>>>>>> origin/dev
Shit

2022-06-16 13:20 UTC, Varriss commented on src/systems/GameSystem.cpp
> +=======
Shit

2022-06-16 13:20 UTC, Varriss commented on src/systems/GameSystem.cpp
> +<<<<<<< HEAD
Shit

2022-06-16 13:20 UTC, Varriss commented on src/systems/GameSystem.cpp
> +>>>>>>> origin/dev
Shit

2022-06-16 13:20 UTC, Varriss commented on src/components/SoundComponent.hpp
> +        std::string sound;
Transform to private

2022-06-16 13:20 UTC, Varriss commented on src/components/SoundComponent.hpp
> +        Sound::SoundState getSoundState() { return _newState; };
Add const to getter methods

2022-06-16 13:20 UTC, Varriss commented on src/components/MusicComponent.hpp
> +        std::string music;
Transform to private

2022-06-16 13:20 UTC, Varriss commented on src/components/MusicComponent.hpp
> +        Music::MusicState getMusicState() { return _newState; };
Add const to getters methods

2022-06-16 13:20 UTC, Varriss commented on src/Sound.hpp
> +        SoundState _state = SoundState::PAUSED;
Transform to Private, make a const getter

2022-06-16 13:20 UTC, Varriss commented on src/Music.hpp
> +            MusicState _state = MusicState::PAUSE;
Transform to private

2022-06-16 15:53 UTC, iDommel approved these changes

2022-06-16 15:58 UTC, iDommel approved these changes

2022-06-16 16:04 UTC, merged